"""make task taskset relation nullable

Revision ID: 2c641048c11e
Revises: be3775bd2adb
Create Date: 2024-01-07 21:42:33.146261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c641048c11e'
down_revision: Union[str, None] = 'be3775bd2adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'taskset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'taskset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
