"""add status

Revision ID: 8d0947121951
Revises: cedbf6739872
Create Date: 2024-01-03 01:30:50.939380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d0947121951"
down_revision: Union[str, None] = "cedbf6739872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("status", sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "status")
    # ### end Alembic commands ###
